import { Model, DataTypes } from 'sequelize';
import { getSequelizeInstance } from '../config/sequelize';

class SustainabilityActivity extends Model {
    public id!: number;
    public pointsAdded!: number;
    public carbonDioxideGenerated!: number;
    public isAutogenerated!: boolean;

    // Relaciones entre entidades
    public userId!: number;

    // Timestamps
    public readonly createdAt!: Date;
    public readonly updatedAt!: Date;
}

SustainabilityActivity.init(
    {
        id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true,
        },
        pointsAdded: {
            type: DataTypes.INTEGER,
            allowNull: false,
        },
        carbonDioxideGenerated: {
            type: DataTypes.DECIMAL(10, 2),
            allowNull: false,
        },
        isAutogenerated: {
            type: DataTypes.BOOLEAN,
            allowNull: false,
        },
        userId: {
            type: DataTypes.INTEGER,
            allowNull: false,
            references: {
                model: 'users',
                key: 'id',
            },
        },
    },
    {
        sequelize: getSequelizeInstance(),
        modelName: 'SustainabilityActivity',
        tableName: 'sustainabilityactivities',
        timestamps: true,
    },
);

export default SustainabilityActivity;
